### ISSUE TITLE
Timerboard is broken ATM

### ISSUE THREAD

**Issue by MonoliYoda** [MonoliYoda/evve_dashboard_dev#2]
Django expects a CSRF token to be passed in inside the POST /ajax/newtimer request. Need to figure out how to do this.

**Comment by SoCariEVE** [comment]
See: https://docs.djangoproject.com/en/dev/ref/csrf/#ajax

It looks like the best method will be to set a `X-CSRFToken` header for every XMLHttpRequest.

There are two relevant settings: `CSRF_USE_SESSIONS` and `CSRF_COOKIE_HTTPONLY`, both of which are unset. This means (1) the CSRF token is stored in a cookie rather than a session, and (2) we may access that cookie with client-side javascript.

Looks like you're using the jQuery `ajax()` function to create the XMLHttpRequest. We can set headers here using the `headers` key in the settings object passed to the function.

**Comment by MonoliYoda** [comment]
Oh okay, interesting. I don't really want to open another pandora's box with trying to learn how to extract the CSRF token from a cookie using JS. Is anyone up for that?

In the meantime, I'm fixing the timerboard, making it at least able to display and add Timers using the `@csrf_exempt` decorator on the AJAX view functions.

**Comment by SoCariEVE** [comment]
There's sample code on the page linked above. I'm already working on it.

Could you point me to how you can tell that a CSRF token is required, and that it's not being passed in? (I need to know what I'm looking for as both "failing" and "succeeding" behaviour.)

**Comment by MonoliYoda** [comment]
In Chrome: `right-click > Inspect > Network` and then try to add a timer. There will be a red line with a 403 Forbidden error.
